import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronsDown, ChevronsUp, ChevronDown, ChevronRight, Plus, Save, Search, Sparkles, Trash2 } from "lucide-react";
import { EmptyState } from "../components/EmptyState";
import { PageHeader } from "../components/PageHeader";
import { api, createTaskId } from "../services/api";
import { useAppStore } from "../stores/appStore";
import type { ChapterSummary, WorkState } from "../types";
import { readable, safeJson, statusText } from "../utils/format";
import { readNumberList, readScroll, writeNumberList, writeScroll } from "../utils/workspaceState";

type Selection = { kind: "full" } | { kind: "volume"; number: number } | { kind: "chapter"; number: number };
const primaryFields = [["章节标题", "title"], ["章节概述", "outline"], ["本章目标", "chapter_goal"], ["主要冲突", "conflict"], ["本章回报", "chapter_payoff"], ["章尾动作", "ending_hook"], ["下一章承接任务", "handoff"]] as const;
const detailFields = [["故事时间", "story_time"], ["承接债", "continuity_debt"], ["开头方式", "opening_mode"], ["开头主体", "opening_subject"], ["开头触发事件", "opening_trigger"], ["上一章锚点", "previous_anchor"], ["首屏冲突", "first_screen_conflict"], ["禁止使用的开头", "forbidden_opening"], ["主要场景", "main_scene"], ["出场人物", "characters_present"], ["线索推进", "clues"], ["新增信息", "new_information"], ["人物变化", "character_change"], ["伏笔安排", "foreshadowing"], ["情绪转折", "emotional_turn"], ["章尾外部锚点", "ending_external_anchor"], ["下一章开场动作", "next_opening_action"], ["下一章连续性债务", "next_continuity_debt"]] as const;

export function OutlinePage() {
  const store = useAppStore(); const queryClient = useQueryClient(); const workId = store.selectedWorkId;
  const workTask = store.tasks.some((task) => Number(task.workId || 0) === Number(workId));
  const query = useQuery({ queryKey: ["outline-state", workId], queryFn: () => api<WorkState>(`/api/works/${workId}/outline-state`), enabled: Boolean(workId) });
  const [selection, setSelection] = useState<Selection>({ kind: "full" }); const [search, setSearch] = useState(""); const [expanded, setExpanded] = useState<number[]>([]); const [fullOutline, setFullOutline] = useState(""); const [volumes, setVolumes] = useState<Array<Record<string, unknown>>>([]); const [chapterForm, setChapterForm] = useState<Record<string, unknown>>({}); const [start, setStart] = useState(0); const [count, setCount] = useState(3); const [transition, setTransition] = useState<Record<string, unknown> | null>(null); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false);
  const outline = query.data?.outline || { full_outline: "", volume_outline: [], chapters: [] };
  const selectedChapterSummary = selection.kind === "chapter" ? outline.chapters.find((item) => Number(item.chapter_number) === selection.number) : undefined;
  const selectedChapterQuery = useQuery({ queryKey: ["outline-chapter", workId, selection.kind === "chapter" ? selection.number : null], queryFn: () => api<{ chapter: ChapterSummary }>(`/api/works/${workId}/chapters/${selection.kind === "chapter" ? selection.number : 0}/outline`), enabled: Boolean(workId && selection.kind === "chapter") });
  const selectedChapter = selectedChapterQuery.data?.chapter || selectedChapterSummary;
  useEffect(() => { setSelection({ kind: "full" }); setSearch(""); setChapterForm({}); setStart(0); setTransition(null); setDirty(false); }, [workId]);
  useEffect(() => {
    if (!query.data) return;
    setStart(Math.max(0, ...outline.chapters.map((chapter) => Number(chapter.chapter_number) || 0)));
  }, [workId, query.data?.work.id]);
  useEffect(() => { store.setNavigationGuard(dirty ? () => window.confirm("大纲或细纲有未保存修改。确定离开当前页面吗？") : null); return () => store.setNavigationGuard(null); }, [dirty]);
  useEffect(() => {
    if (!query.data || dirty) return;
    setFullOutline(outline.full_outline || "");
    setVolumes(outline.volume_outline || []);
    if (selectedChapter) setChapterForm(chapterFormFrom(selectedChapter));
  }, [query.data, selectedChapter?.chapter_number, selectedChapter?.updated_at, dirty]);
  const groups = useMemo(() => groupChapters(outline.chapters, volumes, search), [outline.chapters, volumes, search]);
  const volumeKey = useMemo(() => groupChapters(outline.chapters, volumes, "").map((item) => item.number).join(","), [outline.chapters, volumes]);
  useEffect(() => {
    if (!workId || !groups.length) return;
    const saved = readNumberList(`hi-story:outline-expanded:${workId}`);
    setExpanded(saved === null ? groups.map((item) => item.number) : saved);
    window.setTimeout(() => {
      document.querySelector<HTMLElement>(".outline-layout .split-nav")?.scrollTo({ top: readScroll(`hi-story:outline-tree-scroll:${workId}`) });
      document.querySelector<HTMLElement>(".outline-layout .split-content")?.scrollTo({ top: readScroll(`hi-story:outline-content-scroll:${workId}`) });
    }, 0);
  }, [workId, volumeKey]);
  function updateExpanded(next: number[]) { setExpanded(next); if (workId) writeNumberList(`hi-story:outline-expanded:${workId}`, next); }
  function toggleVolume(number: number) { updateExpanded(expanded.includes(number) ? expanded.filter((item) => item !== number) : [...expanded, number]); }
  function confirmDiscard() { return !dirty || window.confirm("当前内容尚未保存。确定放弃修改并切换吗？"); }
  function chooseSelection(next: Selection) {
    const same = selection.kind === next.kind && (selection.kind === "full" || selection.number === (next as { number: number }).number);
    if (same) return true;
    if (!same && !confirmDiscard()) return false;
    setDirty(false);
    setSelection(next);
    if (next.kind === "chapter") {
      const chapter = outline.chapters.find((item) => Number(item.chapter_number) === next.number);
      setChapterForm(chapter ? chapterFormFrom(chapter) : {});
      setStart(next.number);
      store.selectChapter(next.number);
    }
    return true;
  }
  function updateChapterForm(next: Record<string, unknown>) { setChapterForm(next); setDirty(true); }
  async function saveCurrent() { if (!workId || workTask || saving) { if (workTask && !saving) store.notify("当前作品仍有任务运行，暂时不能保存大纲。", "warning"); return; } setSaving(true); try { if (selection.kind === "chapter") await api(`/api/works/${workId}/chapters/${selection.number}/outline`, { method: "PUT", body: chapterForm }); else await api(`/api/works/${workId}/outline`, { method: "PUT", body: { full_outline: fullOutline, volume_outline: volumes } }); await queryClient.invalidateQueries({ queryKey: ["outline-state", workId] }); if (selection.kind === "chapter") await queryClient.invalidateQueries({ queryKey: ["outline-chapter", workId, selection.number] }); setDirty(false); store.notify(selection.kind === "chapter" ? "章节细纲已保存。" : "大纲已保存。", "success"); } catch (error) { store.notify((error as Error).message, "danger"); } finally { setSaving(false); } }
  async function runGeneration(kind: "outline" | "chapters") { if (!workId || workTask) { if (workTask) store.notify("当前作品已有任务运行，请等待完成或停止后再生成。", "warning"); return; } if (dirty && !window.confirm("当前内容尚未保存。继续生成会以数据库中的已保存内容为准，确定继续吗？")) return; const taskId = createTaskId(kind); const controller = new AbortController(); const firstGeneratedChapter = Math.max(1, start + 1); store.setTask({ id: taskId, kind, title: kind === "outline" ? "生成全书大纲" : "生成章节细纲", detail: "", startedAt: Date.now(), controller, workId }); try { const data = await api<WorkState & { generated_chapters?: Array<Record<string, unknown>>; volume_transition?: Record<string, unknown>; partial_warning?: string }>(`/api/works/${workId}/${kind === "outline" ? "outline" : "chapter-outlines"}`, { method: "POST", signal: controller.signal, body: kind === "outline" ? { task_id: taskId } : { task_id: taskId, start_chapter: firstGeneratedChapter, count } }); setDirty(false); queryClient.setQueryData(["outline-state", workId], data); if (data.volume_transition?.changed) setTransition(data.volume_transition); const generatedNumbers = (data.generated_chapters || []).map((chapter) => Number(chapter.chapter_number) || 0).filter(Boolean); if (kind === "chapters" && generatedNumbers.length) setStart(Math.max(...generatedNumbers)); const generatedMessage = generatedNumbers.length === 1 ? `第 ${generatedNumbers[0]} 章细纲已生成。` : generatedNumbers.length > 1 ? `第 ${Math.min(...generatedNumbers)} 至 ${Math.max(...generatedNumbers)} 章细纲已生成。` : "章节细纲已生成。"; store.notify(data.partial_warning || (kind === "outline" ? "全书大纲已生成。" : generatedMessage), data.partial_warning ? "warning" : "success"); } catch (error) { if ((error as Error).name !== "AbortError") store.notify((error as Error).message, "danger"); } finally { useAppStore.getState().removeTask(taskId); } }
  if (!workId) return <div className="page"><PageHeader title="大纲与细纲" /><EmptyState title="先选择一个作品" /></div>;
  return <div className="page"><PageHeader title="大纲与细纲" description="章节细纲生成时会自动判断是否需要换卷。" actions={<><button className="btn" disabled={workTask || saving} onClick={() => runGeneration("outline")}><Sparkles size={16} />生成全书大纲</button><button className="btn primary" disabled={workTask || saving} onClick={saveCurrent}><Save size={16} />{saving ? "正在保存" : "保存当前内容"}</button></>} />
    <div className="split-page outline-layout"><aside className="split-nav" onScroll={(event) => workId && writeScroll(`hi-story:outline-tree-scroll:${workId}`, event.currentTarget.scrollTop)}><div className="outline-tree-tools"><div className="search-box"><Search size={16} /><input className="input" placeholder="搜索卷或章节" value={search} onChange={(e) => setSearch(e.target.value)} /></div><button className="icon-button" title="全部展开" onClick={() => updateExpanded(groups.map((item) => item.number))}><ChevronsDown size={16} /></button><button className="icon-button" title="全部收起" onClick={() => updateExpanded([])}><ChevronsUp size={16} /></button></div><button className={`tree-item ${selection.kind === "full" ? "active" : ""}`} onClick={() => chooseSelection({ kind: "full" })}>全书大纲</button>{groups.map((group) => <div key={group.number}><button className={`tree-item volume-tree ${selection.kind === "volume" && selection.number === group.number ? "active" : ""}`} onClick={() => { if (chooseSelection({ kind: "volume", number: group.number })) toggleVolume(group.number); }}>{expanded.includes(group.number) ? <ChevronDown size={14} /> : <ChevronRight size={14} />}第 {group.number} 卷 · {group.title}</button>{expanded.includes(group.number) && group.chapters.map((chapter) => <button className={`tree-item child ${selection.kind === "chapter" && selection.number === Number(chapter.chapter_number) ? "active" : ""}`} key={chapter.chapter_number} onClick={() => chooseSelection({ kind: "chapter", number: Number(chapter.chapter_number) })}>第 {chapter.chapter_number} 章 · {chapter.title || "未命名"}<small>{statusText(chapter.status)}</small></button>)}</div>)}</aside>
      <main className="split-content" onScroll={(event) => workId && writeScroll(`hi-story:outline-content-scroll:${workId}`, event.currentTarget.scrollTop)}>{selection.kind === "full" ? <section className="form-section"><h3 className="section-title">全书大纲</h3><label className="field"><textarea className="outline-long" value={fullOutline} onChange={(e) => { setFullOutline(e.target.value); setDirty(true); }} /></label></section> : selection.kind === "volume" ? <VolumeEditor volume={volumes.find((item, index) => Number(item.volume_number || index + 1) === selection.number)} onChange={(next) => { setVolumes(volumes.map((item, index) => Number(item.volume_number || index + 1) === selection.number ? next : item)); setDirty(true); }} /> : selectedChapter ? <ChapterEditor value={chapterForm} onChange={updateChapterForm} /> : <EmptyState title="没有找到这章细纲" />}</main>
      <aside className="split-aside"><h3>细纲生成</h3><label className="field">续写基准章<input type="number" min="0" value={start} disabled={workTask || saving} onChange={(e) => setStart(Math.max(0, Number(e.target.value)))} /></label><label className="field">生成章数<input type="number" min="1" max="30" value={count} disabled={workTask || saving} onChange={(e) => setCount(Math.min(30, Math.max(1, Number(e.target.value))))} /></label><div className="generation-range">将生成：第 {Math.max(1, start + 1)}{count > 1 ? ` 至 ${Math.max(1, start + 1) + count - 1}` : ""} 章</div><button className="btn primary full-button" disabled={workTask || saving} onClick={() => runGeneration("chapters")}><Sparkles size={16} />生成章节细纲</button><div className="summary-block"><h4>卷状态</h4>{selection.kind === "volume" ? <pre className="readable">{readable(volumes.find((item, index) => Number(item.volume_number || index + 1) === selection.number))}</pre> : <p>选择一个卷后显示目标章数、退出条件和里程碑。</p>}</div>{transition && <div className="transition-notice"><strong>已自动切换分卷</strong><pre className="readable">{readable(transition)}</pre></div>}</aside>
    </div></div>;
}
function chapterFormFrom(chapter: ChapterSummary) { const raw = chapter as Record<string, unknown>; const detail = safeJson(raw.outline_json, {}) as Record<string, unknown>; const source = { ...detail, ...raw }; const sceneCards = Array.isArray(source.scene_cards) ? source.scene_cards : safeJson(source.scene_cards_json, []); return { title: String(source.title || ""), outline: String(source.outline || ""), ending_hook: String(source.ending_hook || ""), volume_number: Number(source.volume_number || 1), ...Object.fromEntries(primaryFields.filter(([, key]) => !["title", "outline", "ending_hook"].includes(key)).map(([, key]) => [key, source[key] ?? ""])), ...Object.fromEntries(detailFields.map(([, key]) => [key, source[key] ?? ""])), scene_cards: Array.isArray(sceneCards) ? sceneCards : [] }; }
function ChapterEditor({ value, onChange }: { value: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void }) { const scenes = Array.isArray(value.scene_cards) ? value.scene_cards as Array<Record<string, unknown>> : []; const setScenes = (next: Array<Record<string, unknown>>) => onChange({ ...value, scene_cards: next }); return <><section className="form-section"><div className="form-grid">{primaryFields.map(([label, key]) => <label className={`field ${key === "outline" ? "span-all" : ""}`} key={key}>{label}<textarea rows={key === "outline" ? 6 : 3} value={String(value[key] || "")} onChange={(e) => onChange({ ...value, [key]: e.target.value })} /></label>)}<label className="field">所属卷<input type="number" min="1" value={Number(value.volume_number || 1)} onChange={(e) => onChange({ ...value, volume_number: Number(e.target.value) })} /></label></div></section><details className="details-section"><summary>展开执行细节</summary><div className="form-grid">{detailFields.map(([label, key]) => <label className="field" key={key}>{label}<textarea rows={2} value={Array.isArray(value[key]) ? (value[key] as unknown[]).join("、") : String(value[key] || "")} onChange={(e) => onChange({ ...value, [key]: e.target.value })} /></label>)}</div><div className="scene-editor"><div className="scene-editor-head"><h4>场景任务</h4><button className="btn small" onClick={() => setScenes([...scenes, {}])}><Plus size={14} />新增场景</button></div>{scenes.map((scene, index) => <section className="scene-row" key={index}><div className="scene-row-head"><strong>场景 {index + 1}</strong><button className="icon-button danger-icon" title="删除场景" onClick={() => setScenes(scenes.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={14} /></button></div><div className="form-grid">{[["场景目标","scene_goal"],["阻碍","obstacle"],["信息增量","information_gain"],["情绪变化","emotional_shift"],["场景出口","scene_exit"]].map(([label,key]) => <label className={`field ${key === "scene_goal" || key === "scene_exit" ? "span-all" : ""}`} key={key}>{label}<textarea rows={2} value={String(scene[key] || "")} onChange={(event) => setScenes(scenes.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: event.target.value } : item))} /></label>)}</div></section>)}</div></details></>; }
function VolumeEditor({ volume, onChange }: { volume?: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void }) { if (!volume) return <EmptyState title="暂无分卷信息" description="先生成全书大纲，或在全书大纲中补充分卷规划。" />; const fields = [["卷名", "title"], ["本卷目标", "goal"], ["退出条件", "exit_condition"], ["最少章节", "min_chapters"], ["目标章节", "target_chapters"], ["软上限", "soft_max_chapters"], ["硬上限", "hard_max_chapters"], ["必经里程碑", "required_milestones"]] as const; return <section className="form-section"><h3 className="section-title">第 {String(volume.volume_number || "")} 卷</h3><div className="form-grid">{fields.map(([label, key]) => <label className="field" key={key}>{label}{key.includes("chapters") ? <input type="number" value={Number(volume[key] || 0)} onChange={(e) => onChange({ ...volume, [key]: Number(e.target.value) })} /> : <textarea rows={3} value={Array.isArray(volume[key]) ? (volume[key] as unknown[]).join("\n") : String(volume[key] || "")} onChange={(e) => onChange({ ...volume, [key]: e.target.value })} />}</label>)}</div></section>; }
function groupChapters(chapters: ChapterSummary[], volumes: Array<Record<string, unknown>>, search: string) { const map = new Map<number, { number: number; title: string; chapters: ChapterSummary[] }>(); volumes.forEach((volume, index) => { const number = Number(volume.volume_number || index + 1); map.set(number, { number, title: String(volume.title || "未命名"), chapters: [] }); }); chapters.forEach((chapter) => { const detail = safeJson(chapter.outline_json, {}); const number = Number(chapter.volume_number || detail.volume_number || 1); if (!map.has(number)) map.set(number, { number, title: `第${number}卷`, chapters: [] }); if (!search || `${chapter.title || ""}${chapter.outline || ""}${map.get(number)!.title}`.includes(search)) map.get(number)!.chapters.push(chapter); }); return [...map.values()].filter((item) => !search || item.chapters.length || item.title.includes(search)).sort((a, b) => a.number - b.number); }
