import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileCheck2, Lock, Sparkles, Trash2, Unlock } from "lucide-react";
import { EmptyState } from "../components/EmptyState";
import { PageHeader } from "../components/PageHeader";
import { api, createTaskId } from "../services/api";
import { useAppStore } from "../stores/appStore";
import type { Work, WorkState } from "../types";
import { formatTime, readable } from "../utils/format";

const styleFields = [["叙事节奏", "pace"], ["语言风格", "language"], ["情绪底色", "mood"], ["叙事视角", "pov"], ["单章字数", "chapter_words"], ["爽点密度", "payoff"]] as const;
const contractFields = [["题材核心", "genre_core"], ["读者承诺", "reader_promise"], ["冲突发动机", "conflict_engine"], ["章节回报", "chapter_payoff"], ["开头偏好", "opening_preference"], ["避免事项", "avoid"], ["语言质感", "language_texture"]] as const;

export function ProjectPage() {
  const store = useAppStore(); const queryClient = useQueryClient(); const workId = store.selectedWorkId;
  const query = useQuery({ queryKey: ["work", workId], queryFn: () => api<WorkState>(`/api/works/${workId}`), enabled: Boolean(workId) });
  const [form, setForm] = useState<Record<string, string | number>>({}); const [contract, setContract] = useState<Record<string, string>>({}); const [plan, setPlan] = useState<Record<string, unknown> | null>(null); const [planText, setPlanText] = useState("");
  useEffect(() => { const work = query.data?.work; if (!work) return; setForm({ title: work.title || "", idea: String(work.idea || ""), genre: String(work.genre || ""), platform: String(work.platform || ""), target_words: Number(work.target_words || 0), ...parseStyle(String(work.style || "")) }); setContract(Object.fromEntries(contractFields.map(([, key]) => [key, String(query.data?.book_contract?.[key] || "")]))); }, [query.data?.work.updated_at, query.data?.book_contract]);
  const locked = Boolean(Number(query.data?.work.settings_locked || 0));
  const inputs = useMemo(() => ({ title: String(form.title || "").trim(), idea: String(form.idea || "").trim(), genre: String(form.genre || "").trim(), platform: String(form.platform || "").trim(), target_words: Number(form.target_words || 0), style: styleFields.map(([label, key]) => form[key] ? `${label}：${String(form[key]).trim()}` : "").filter(Boolean).join("\n"), forbidden_tropes: "", protagonist_preference: "", reader_profile: "", locked_facts: contract.avoid || "", writing_controls: "" }), [form, contract.avoid]);
  const save = useMutation({ mutationFn: async () => { if (!workId) throw new Error("请先选择作品。"); await api(`/api/works/${workId}`, { method: "PUT", body: inputs }); return api<WorkState>(`/api/works/${workId}/book-contract`, { method: "PUT", body: contract }); }, onSuccess: (data) => { applyState(data, queryClient, store); store.notify("作品设定与题材契约已保存。", "success"); }, onError: (error) => store.notify((error as Error).message, "danger") });
  async function generatePlan() { if (!workId || store.task) return; const taskId = createTaskId("plan"); const controller = new AbortController(); store.setTask({ id: taskId, kind: "plan", title: "生成设定草稿", detail: "", startedAt: Date.now(), controller, workId }); try { const data = await api<{ plan: Record<string, unknown>; readable: string }>(`/api/works/${workId}/plan-draft`, { method: "POST", signal: controller.signal, body: { ...inputs, task_id: taskId } }); setPlan(data.plan); setPlanText(data.readable || readable(data.plan)); store.notify("设定草稿已生成。", "success"); } catch (error) { if ((error as Error).name !== "AbortError") store.notify((error as Error).message, "danger"); } finally { if (useAppStore.getState().task?.id === taskId) store.setTask(null); } }
  async function applyPlan() { if (!workId || !plan) return; try { const data = await api<WorkState>(`/api/works/${workId}/apply-plan`, { method: "POST", body: { plan, inputs } }); applyState(data, queryClient, store); setPlan(null); setPlanText(""); store.notify("设定草稿已采用。", "success"); } catch (error) { store.notify((error as Error).message, "danger"); } }
  async function toggleLock() { if (!workId) return; try { const data = await api<WorkState>(`/api/works/${workId}/settings-lock`, { method: "PUT", body: { locked: !locked } }); applyState(data, queryClient, store); store.notify(locked ? "作品设定已解锁。" : "作品设定已锁定。", "success"); } catch (error) { store.notify((error as Error).message, "danger"); } }
  async function deleteWork() { if (!workId || !window.confirm(`确定删除《${query.data?.work.title || "当前作品"}》吗？`)) return; try { const data = await api<{ works: Work[] }>(`/api/works/${workId}`, { method: "DELETE" }); store.setWorks(data.works || []); store.selectWork(data.works?.[0]?.id || null); queryClient.clear(); store.notify("作品已删除。", "success"); } catch (error) { store.notify((error as Error).message, "danger"); } }
  if (!workId) return <div className="page"><PageHeader title="作品设定" /><EmptyState title="先新建一个作品" description="作品的核心设定、写作方向和题材契约会集中在这里。" /></div>;
  return <div className="page"><PageHeader title="作品设定" description="锁定后可避免误改全书基础约束。" actions={<><button className="btn" onClick={toggleLock}>{locked ? <Unlock size={16} /> : <Lock size={16} />}{locked ? "解锁设定" : "锁定设定"}</button><button className="btn" disabled={locked || Boolean(store.task)} onClick={generatePlan}><Sparkles size={16} />生成设定草稿</button><button className="btn primary" disabled={locked || save.isPending} onClick={() => save.mutate()}><FileCheck2 size={16} />保存设定</button></>} />
    <div className="project-layout"><main className="project-page"><div className="content-width"><FormSection title="核心设定"><div className="form-grid"><Field label="小说名称" value={form.title} disabled={locked} onChange={(v) => setForm({ ...form, title: v })} /><Field label="题材" value={form.genre} disabled={locked} onChange={(v) => setForm({ ...form, genre: v })} /><Field label="一句话创意" value={form.idea} disabled={locked} area onChange={(v) => setForm({ ...form, idea: v })} /><Field label="目标平台" value={form.platform} disabled={locked} onChange={(v) => setForm({ ...form, platform: v })} /><Field label="目标字数" value={form.target_words} disabled={locked} type="number" onChange={(v) => setForm({ ...form, target_words: Number(v) })} /></div></FormSection><FormSection title="写作方向"><div className="form-grid three">{styleFields.map(([label, key]) => <Field key={key} label={label} value={form[key]} disabled={locked} onChange={(v) => setForm({ ...form, [key]: v })} />)}</div></FormSection><FormSection title="题材契约卡"><div className="form-grid">{contractFields.map(([label, key]) => <Field key={key} label={label} value={contract[key]} disabled={locked} area onChange={(v) => setContract({ ...contract, [key]: v })} />)}</div></FormSection><div className="danger-zone"><div><strong>删除作品</strong><p>此操作不可撤销，请先确认作品已导出或备份。</p></div><button className="btn danger" onClick={deleteWork}><Trash2 size={15} />删除作品</button></div></div></main><aside className="project-aside"><h3>作品概况</h3><Metric label="章节数量" value={query.data?.chapters?.length || 0} /><Metric label="设定状态" value={locked ? "已锁定" : "可编辑"} /><Metric label="最近修改" value={formatTime(query.data?.work.updated_at) || "暂无"} /><div className="summary-block"><h4>下一步</h4><p>{String(query.data?.workflow_state?.next_action || "完善设定后生成全书大纲。")}</p></div>{plan && <div className="plan-preview"><h3>待采用的设定草稿</h3><pre className="readable">{planText}</pre><button className="btn primary" onClick={applyPlan}>采用这份设定</button><button className="btn quiet" onClick={() => { setPlan(null); setPlanText(""); }}>放弃草稿</button></div>}</aside></div></div>;
}
function FormSection({ title, children }: { title: string; children: ReactNode }) { return <section className="form-section"><h3 className="section-title">{title}</h3>{children}</section>; }
function Field({ label, value, onChange, area = false, type = "text", disabled = false }: { label: string; value: unknown; onChange: (value: string) => void; area?: boolean; type?: string; disabled?: boolean }) { return <label className={`field ${area ? "span-all" : ""}`}>{label}{area ? <textarea rows={3} value={String(value || "")} disabled={disabled} onChange={(e) => onChange(e.target.value)} /> : <input type={type} value={String(value ?? "")} disabled={disabled} onChange={(e) => onChange(e.target.value)} />}</label>; }
function Metric({ label, value }: { label: string; value: ReactNode }) { return <div className="metric-row"><span>{label}</span><strong>{value}</strong></div>; }
function parseStyle(style: string) { const labels = Object.fromEntries(styleFields.map(([label, key]) => [label, key])); const result: Record<string, string> = {}; style.split(/\r?\n/).forEach((line) => { const match = line.match(/^([^：:]+)[：:]\s*(.*)$/); if (match && labels[match[1]]) result[labels[match[1]]] = match[2]; }); return result; }
function applyState(data: WorkState, queryClient: ReturnType<typeof useQueryClient>, store: ReturnType<typeof useAppStore.getState>) { queryClient.setQueryData(["work", data.work.id], data); queryClient.setQueryData(["works"], { works: data.works || [] }); store.setWorks(data.works || store.works); }
